### PR TITLE
Implement recursive transform reduce

### PR DESCRIPTION
**Pull request by tpadioleau**

### CODE REVIEW

**Review by jbigot — DISMISSED** [review]
looks great :+1:

**Comment by tpadioleau** [comment]
Shall we introduce `transform_reduce_n` ?

**Comment by jbigot** [comment]
Yes, I guess a `transform_reduce_n` would make sense, but it can be done in a separate MR

**Comment by tpadioleau** [comment]
Do you understand why there is no pipeline running ?

**Review by jbigot — DISMISSED** [review]

**Review by jbigot — APPROVED** [review]

**Pull request merged**
