### PR TITLE
Introduce DiscreteElement class

### PR DESCRIPTION
**Pull request by tpadioleau**

### CODE REVIEW

**Comment by tpadioleau** [comment]
@jbigot what do you think of renaming TaggedVector into DiscreteVector (thus removing the element parameter template) ? And replacing DiscreteCoordinate by DiscreteElement (no element template either ?) ?

**Comment by jbigot** [comment]
Isn't there a lot of implementation in common that could be shared?

**Comment by tpadioleau** [comment]
What implementation are you thinking of ?

**Comment by tpadioleau** [comment]
Let `a, b` be a discrete element, `u, v` discrete vectors and `x` an integral, we need to define the following operators

- internal operations `+u`, `-u`, `x * u`, `u+v`, `u-v`,
- right external operations `a+u`, `a-u`
- external operation `a-b`

I agree that it would make sense to allow implicit conversion of an integral to a 1-d discrete vector

**Review by jbigot — APPROVED** [review]

**Pull request merged**
