### PR TITLE
Add a clang-tidy test

### PR DESCRIPTION
**Pull request by tpadioleau**

### CODE REVIEW

**Review by jbigot — APPROVED** [review]
nice!

**Comment by tpadioleau** [comment]
Well yes but I am not able to build the docker images successfully. Shall we split them into smaller images ?

**Review by tpadioleau — COMMENTED** [review]
ok

**Comment by tpadioleau** [comment]
@jbigot @blegouix what do you think ? This currently enables `bugprone-reserved-identifier` and `hicpp-avoid-c-arrays` clang-tidy checks. Do you think there is any benefit of putting the checks into a `.clang-tidy` file at the root of the project ?

**Comment by jbigot** [comment]
> @jbigot @blegouix what do you think ? This currently enables `bugprone-reserved-identifier` and `hicpp-avoid-c-arrays` clang-tidy checks. Do you think there is any benefit of putting the checks into a `.clang-tidy` file at the root of the project ?

To me, that would be nice so as to use it locally also

**Review by jbigot — APPROVED** [review]
nice!

**Pull request merged**
