### PR TITLE
[draft] support multiple named dimensions using similar discretizations of the same continuous dimension

### PR DESCRIPTION
**Pull request by jbigot**

### CODE REVIEW

**Comment by tpadioleau** [comment]
@jbigot tell me when to review it.

**Comment by jbigot** [comment]
It's not ready yet, I mostly wanted the tests to run. I forgot to mark it as draft and don't see a way to change it after the fact

**Comment by jbigot** [comment]
ok, found it

**Comment by tpadioleau** [comment]
choosing #121

**Pull request closed without merging**
