### PR TITLE
Successful build of gyselalibxx is not a requirement anymore

### PR DESCRIPTION
**Pull request by tpadioleau**

### CODE REVIEW

**Review by jbigot — APPROVED** [review]
looks good

**Comment by tpadioleau** [comment]
> looks good

I cannot find where to trigger gyselalibxx build ?

**Comment by jbigot** [comment]
I believe this will appear in the "actions" tab once in main

**Comment by tpadioleau** [comment]
> I'd remove both, if we remove the action on gitlab side, the trigger will return an error

Ok good point

**Comment by tpadioleau** [comment]
I think we are good

**Review by jbigot — APPROVED** [review]

**Pull request merged**
